"""Add notification preferences and scheduled reminders

Revision ID: 42ec7d3e6c65
Revises: 68a3dae234b1
Create Date: 2025-07-13 10:35:47.974724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ec7d3e6c65'
down_revision = '68a3dae234b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_times', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_start', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_end', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('weekend_reminders', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weekend_reminders')
        batch_op.drop_column('quiet_hours_end')
        batch_op.drop_column('quiet_hours_start')
        batch_op.drop_column('quiet_hours_enabled')
        batch_op.drop_column('reminder_times')

    # ### end Alembic commands ###
