"""Initial migration with conversation state

Revision ID: 68a3dae234b1
Revises: 
Create Date: 2025-07-12 13:19:55.644335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a3dae234b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_step', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_state', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conversation_step', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('conversation_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('conversation_updated')
        batch_op.drop_column('conversation_step')
        batch_op.drop_column('conversation_state')

    with op.batch_alter_table('message_history', schema=None) as batch_op:
        batch_op.drop_column('conversation_step')

    # ### end Alembic commands ###
